### ISSUE TITLE
Execution time experiments

### ISSUE THREAD

**Issue by juanmed** [vroulet/ilqc#1]
Hello,

Thank for sharing the code for your paper. I was wondering if you have any official or non-official time execution measurements for the algorithms presented in your paper? I will appreciate some insights in this sense. Thanks!

**Comment by vroulet** [comment]
Hello Juan,

Thank you for your interest in our paper! I am currently reformatting the
code, it should be done in one week or two, I will include these measures
in the new code. I keep you updated as soon as possible. The time execution
depends on the machine and it would be easier for you to compare on your
machine. If you need those times urgently I can work on that.

A few remarks:
- The normal ILQR suffers from a line-search at each iteration by an armijo
rule. Without this line-search its behavior is chaotic. The regularized
version does not suffer from that but needs an appropriate tuning in the
burn-in phase. I am currently implementing line-searches for the
regularized version too that should enhance its behavior.
- The accelerated ILQR makes two steps at each iteration. The acceleration
it provides in terms of iterations is not sufficient for getting superior
behavior in terms of time. In other words, the accelerated version was an
interesting try that worked for deep neural networks but not here.
Regularized Gauss-Newton methods are all about the choice of the step-size
that balances between a simple gradients step and a full gauss-Newton step.
Better behavior should be given by appropriate line-searches.
- Be careful the name ILQR has been used for different algorithms by the
same author. Our implementation is the one of the original paper.

**Comment by juanmed** [comment]
@vroulet Thanks for your detailed feedback. If possible, I will appreciate you can upload (maybe to a different branch) the scripts you use for execution time measurements if you dont plan to make them part of master branch. I plan to try this on embedded platforms, namely Jetson TX2 and Nano.   

Based on your comments, I will dig deeper into the references in your paper. Thanks!
